ALTER TYPE "Protocol" ADD VALUE IF NOT EXISTS 'DOKODEMO_DOOR';

ALTER TABLE "inbounds"
  ADD COLUMN IF NOT EXISTS "dokodemoTargetPort" INTEGER,
  ADD COLUMN IF NOT EXISTS "dokodemoNetwork" TEXT,
  ADD COLUMN IF NOT EXISTS "dokodemoFollowRedirect" BOOLEAN NOT NULL DEFAULT false;
