ARG XRAY_BASE_IMAGE=ghcr.io/xtls/xray-core:latest
FROM ${XRAY_BASE_IMAGE}

# Copy default config
COPY xray/config.json /etc/xray/config.json

EXPOSE 443 80 10085

CMD ["run", "-config", "/etc/xray/config.json"]
